-- Tablas del componente Terminales: estaciones, sus fotos y sus conectores (RF04, RF05).
--
-- Nombre del archivo con timestamp, NUNCA V1/V2/V3: con numeración secuencial dos personas
-- escriben el mismo número la misma tarde. Ver README, "Migraciones".
--
-- Sin calificar el schema: lo pone Flyway (spring.flyway.schemas=core).

CREATE TABLE stations (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(120)     NOT NULL,
    address   VARCHAR(255)     NOT NULL,
    latitude  DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    -- Operador dueño. Todavía sin clave foránea: la tabla de usuarios no existe (ECO-23).
    owner_id  BIGINT           NOT NULL,
    -- La baja es lógica: una estación puede tener reservas y sesiones históricas colgando.
    active    BOOLEAN          NOT NULL DEFAULT TRUE
);

-- La búsqueda de RF07 filtra por un recuadro de latitud/longitud antes de calcular
-- distancias. Sin este índice, cada consulta recorre la tabla entera.
CREATE INDEX idx_stations_location ON stations (latitude, longitude);

CREATE TABLE station_photos (
    station_id BIGINT       NOT NULL REFERENCES stations (id),
    url        VARCHAR(500) NOT NULL
);

CREATE INDEX idx_station_photos_station ON station_photos (station_id);

CREATE TABLE connectors (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id         BIGINT        NOT NULL REFERENCES stations (id),
    -- Los enums se guardan como texto y no como ordinal: agregar un valor nuevo no debe
    -- correr el significado de los que ya están guardados.
    connector_type     VARCHAR(20)   NOT NULL,
    max_power_kw       NUMERIC(6, 2) NOT NULL,
    operational_status VARCHAR(20)   NOT NULL
);

CREATE INDEX idx_connectors_station ON connectors (station_id);
