-- Tabla de Esquemas Tarifarios del componente ServicioDeTarificacion (ECO-29, ECO-30, RF06).

CREATE TABLE tariff_schemes (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_id            BIGINT NOT NULL UNIQUE,
    strategy_type           VARCHAR(30) NOT NULL,
    kwh_rate                NUMERIC(10, 2) NOT NULL,
    deposit_amount          NUMERIC(10, 2) NOT NULL,
    excess_penalty_per_min  NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    peak_kwh_rate           NUMERIC(10, 2) DEFAULT NULL,
    active                  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tariff_schemes_connector FOREIGN KEY (connector_id) REFERENCES connectors (id) ON DELETE CASCADE
);

CREATE INDEX idx_tariff_schemes_connector ON tariff_schemes (connector_id);
