-- Datos de ejemplo del componente Terminales: 15 estaciones de CABA, GBA y La Plata con sus
-- conectores (RF04, RF05), para que la búsqueda geolocalizada de RF07 tenga contra qué correr.
--
-- Va como migración de Flyway y no como data.sql para que sea el mismo mecanismo que el resto
-- del esquema: quien levante el proyecto ve exactamente las mismas filas, sin pasos extra.
--
-- Las coordenadas son reales: si fueran inventadas, el filtro por radio devolvería resultados
-- sin sentido y no se podría distinguir un bug de la búsqueda de un dato malo.

-- IDs explícitos: los conectores necesitan referenciar cada estación y hacerlo por nombre
-- obligaría a un subselect por fila. La columna es GENERATED BY DEFAULT, así que acepta el
-- valor, pero NO adelanta su secuencia; el RESTART del final la reposiciona. Sin eso, el
-- primer alta desde la aplicación intentaría el id 1 y chocaría con la clave primaria.
--
-- owner_id 1 para todas: la tabla de usuarios todavía no existe (ECO-23) y la columna no tiene
-- clave foránea, así que el valor es un marcador que se corrige cuando haya operadores reales.
INSERT INTO stations (id, name, address, latitude, longitude, owner_id, active) VALUES
    ( 1, 'Recarga Obelisco',        'Av. 9 de Julio 1000, CABA',            -34.6037, -58.3816, 1, TRUE),
    ( 2, 'Punto Puerto Madero',     'Olga Cossettini 1200, CABA',           -34.6106, -58.3625, 1, TRUE),
    ( 3, 'Estación Palermo Soho',   'Jorge Luis Borges 1700, CABA',         -34.5883, -58.4306, 1, TRUE),
    ( 4, 'Recarga Recoleta',        'Av. Quintana 500, CABA',               -34.5875, -58.3936, 1, TRUE),
    ( 5, 'Punto Retiro',            'Av. del Libertador 200, CABA',         -34.5920, -58.3740, 1, TRUE),
    ( 6, 'Estación Belgrano',       'Av. Cabildo 2200, CABA',               -34.5610, -58.4560, 1, TRUE),
    ( 7, 'Recarga Núñez',           'Av. Figueroa Alcorta 7500, CABA',      -34.5453, -58.4497, 1, TRUE),
    ( 8, 'Punto Villa Urquiza',     'Av. Triunvirato 4300, CABA',           -34.5730, -58.4900, 1, TRUE),
    ( 9, 'Estación Caballito',      'Av. Rivadavia 4900, CABA',             -34.6180, -58.4360, 1, TRUE),
    (10, 'Recarga Flores',          'Av. Rivadavia 6900, CABA',             -34.6280, -58.4640, 1, TRUE),
    (11, 'Punto La Boca',           'Av. Almirante Brown 1100, CABA',       -34.6345, -58.3630, 1, TRUE),
    (12, 'Estación Vicente López',  'Av. del Libertador 1900, Vicente López', -34.5290, -58.4790, 1, TRUE),
    (13, 'Recarga San Isidro',      'Av. Centenario 1500, San Isidro',      -34.4707, -58.5070, 1, TRUE),
    (14, 'Punto Tigre',             'Av. Cazón 1300, Tigre',                -34.4260, -58.5796, 1, TRUE),
    (15, 'Estación La Plata',       'Av. 7 y 50, La Plata',                 -34.9205, -57.9536, 1, TRUE);

-- Mezcla deliberada, no decorativa. Cada filtro de SearchCriteria tiene que poder distinguir
-- algo con estos datos:
--   * onlyAvailable    -> la estación 11 tiene los dos conectores fuera de servicio, así que
--                         desaparece al activarlo y es la prueba de que el filtro hace algo.
--   * minimumPowerKw   -> las potencias van de 7.20 a 180.00; pedir 50 recorta la mitad.
--   * connectorType    -> los tres tipos aparecen en estaciones distintas, no todos en todas.
INSERT INTO connectors (station_id, connector_type, max_power_kw, operational_status) VALUES
    ( 1, 'CCS2',    150.00, 'AVAILABLE'),
    ( 1, 'CCS2',    150.00, 'OCCUPIED'),
    ( 1, 'CHADEMO',  50.00, 'AVAILABLE'),
    ( 2, 'CCS2',    180.00, 'AVAILABLE'),
    ( 2, 'CCS2',    180.00, 'AVAILABLE'),
    ( 2, 'TYPE_2',   22.00, 'AVAILABLE'),
    ( 3, 'TYPE_2',   22.00, 'OCCUPIED'),
    ( 3, 'TYPE_2',   11.00, 'AVAILABLE'),
    ( 4, 'CCS2',     50.00, 'AVAILABLE'),
    ( 4, 'CHADEMO',  50.00, 'OUT_OF_SERVICE'),
    ( 5, 'CCS2',    150.00, 'OCCUPIED'),
    ( 5, 'TYPE_2',   11.00, 'AVAILABLE'),
    ( 6, 'CCS2',     60.00, 'AVAILABLE'),
    ( 6, 'CHADEMO',  50.00, 'OCCUPIED'),
    ( 7, 'CCS2',    120.00, 'AVAILABLE'),
    ( 7, 'CCS2',    120.00, 'OUT_OF_SERVICE'),
    ( 7, 'TYPE_2',   22.00, 'AVAILABLE'),
    -- Única estación con carga lenta y nada más: la que se cae al filtrar por potencia mínima.
    ( 8, 'TYPE_2',    7.20, 'AVAILABLE'),
    ( 9, 'CCS2',     50.00, 'AVAILABLE'),
    ( 9, 'TYPE_2',   11.00, 'OCCUPIED'),
    (10, 'CHADEMO',  50.00, 'AVAILABLE'),
    (10, 'TYPE_2',   22.00, 'AVAILABLE'),
    -- Estación entera fuera de servicio.
    (11, 'CCS2',     50.00, 'OUT_OF_SERVICE'),
    (11, 'TYPE_2',   11.00, 'OUT_OF_SERVICE'),
    (12, 'CCS2',    150.00, 'AVAILABLE'),
    (12, 'CHADEMO',  50.00, 'AVAILABLE'),
    (13, 'CCS2',    180.00, 'AVAILABLE'),
    (13, 'CCS2',     60.00, 'OCCUPIED'),
    (13, 'TYPE_2',   22.00, 'AVAILABLE'),
    (14, 'CCS2',     50.00, 'AVAILABLE'),
    (14, 'TYPE_2',   11.00, 'AVAILABLE'),
    (15, 'CCS2',    150.00, 'AVAILABLE'),
    (15, 'CHADEMO',  50.00, 'OCCUPIED'),
    (15, 'TYPE_2',   22.00, 'AVAILABLE');

-- Reposiciona las secuencias de identidad después de los ids explícitos de arriba.
ALTER TABLE stations ALTER COLUMN id RESTART WITH 16;
ALTER TABLE connectors ALTER COLUMN id RESTART WITH 35;
