-- Medios de pago del conductor, del componente Pagos (RF02, ECO-26).
--
-- Nombre con timestamp, NUNCA V1/V2/V3. Ver README, "Migraciones".
-- Sin calificar el schema: lo pone Flyway (spring.flyway.schemas=integration).

CREATE TABLE payment_methods (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Conductor dueño. Sin clave foránea a propósito, y no por olvido: la tabla de usuarios
    -- vive en el schema de ecopedia-core, que es OTRO artefacto. Una FK entre los dos ataría
    -- dos servicios a compartir base para siempre, que es justo lo que la separación en
    -- artefactos evita. La integridad la sostiene el token: el id sale del JWT que firmó
    -- Usuarios, así que solo llegan acá ids que ese componente emitió.
    -- Es el mismo criterio con el que stations.owner_id quedó sin FK.
    driver_id     BIGINT       NOT NULL,

    -- Lo ÚNICO que se guarda de la tarjeta (RF02).
    --
    -- No hay columna para el número completo, y esa ausencia es el requisito: si la columna
    -- existiera "por las dudas", tarde o temprano alguien la llena. El número viaja del
    -- formulario a la pasarela y no se persiste en ningún punto del camino.
    brand         VARCHAR(20)  NOT NULL,
    last_four     VARCHAR(4)   NOT NULL,

    -- El token que devolvió la pasarela. Es lo que se usa para cobrar: reemplaza al número.
    gateway_token VARCHAR(255) NOT NULL UNIQUE,

    -- Vencimiento. Se guarda para poder mostrar "vence 09/29" y para descartar tarjetas
    -- vencidas antes de intentar un cobro que la pasarela va a rechazar igual.
    expiry_month  INTEGER      NOT NULL,
    expiry_year   INTEGER      NOT NULL,

    -- Etiqueta que elige el conductor ("la del laburo"). Opcional: con dos VISA terminadas
    -- en dígitos parecidos, los últimos cuatro no alcanzan para distinguirlas.
    label         VARCHAR(60),

    -- La baja es lógica. Una tarjeta dada de baja puede tener cobros históricos y deudas
    -- pendientes (RNF06) colgando de su token; borrar la fila los dejaría huérfanos.
    active        BOOLEAN      NOT NULL DEFAULT TRUE,

    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Toda consulta de este componente arranca por "las tarjetas de este conductor".
CREATE INDEX idx_payment_methods_driver ON payment_methods (driver_id, active);
