-- Tabla de reservas del componente Reservas / BookingService (ECO-31).
--
-- Guarda las reservas CONFIRMADAS. La retención previa —el slot que no está ni libre ni vendido
-- mientras el conductor confirma— no pasa por acá: es estado conversacional y vive en memoria
-- del componente, que es justamente lo que lo vuelve stateful. Ver BookingServiceImpl.
--
-- connector_id y driver_id NO tienen clave foránea, y es a propósito: los conectores y los
-- usuarios viven en el schema de ecopedia-core, que es otro artefacto con su propio Flyway. Una
-- FK entre schemas ataría el despliegue de los dos procesos; la existencia del conector se
-- verifica contra core por REST antes de retener el slot.

CREATE TABLE bookings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_id BIGINT      NOT NULL,
    driver_id    BIGINT      NOT NULL,
    window_start TIMESTAMP WITH TIME ZONE NOT NULL,
    window_end   TIMESTAMP WITH TIME ZONE NOT NULL,
    status       VARCHAR(20) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_bookings_window CHECK (window_end > window_start)
);

-- La consulta que más se va a repetir: "¿qué reservas tiene este conector que se crucen con
-- esta ventana?" (ECO-33). Por eso el índice empieza por el conector.
CREATE INDEX idx_bookings_connector_window ON bookings (connector_id, window_start, window_end);
CREATE INDEX idx_bookings_driver ON bookings (driver_id);
